# This is for the Microsoft Assessments Build Pipeline. Please don't change without
# talking to v-magran, David.Stanford

trigger:
  branches:
    include:
    - master
  paths:
      include:
      - /data/pnp-questions.json
      exclude:
      - /


pr: none

pool:
  vmImage: ubuntu-latest

steps:
- script: echo nothing to do here!
  displayName: 'Starting AzDO Build'
